# Generated by Django 3.2 on 2021-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_scheduler', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Chat id'),
        ),
    ]
