# Generated by Django 3.2 on 2021-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_scheduler', '0003_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Chat name'),
        ),
    ]
